[package]
name    = "neuralis"
version = "1.0.0"

[dependencies]
InitiaStdlib = { local = "/tmp/movevm/precompile/modules/initia_stdlib" }

[addresses]
neuralis     = "0xE3659695DCBAAE0CAEAC70B0F9C36DAEC936CB8B"
std          = "0x1"
initia_std   = "0x1"
